---
title: "data-wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparing Sternberg data for analysis

Step one: export data from JATOS server (I have done this for you already)
Step two: use OpenSesame to convert raw data from JATOS text file to .csv file

```{r}
# Clear global environment. Not really necessary, but it is an old habit
rm(list = ls())
```

```{r}
# Load extra functions to make our life easier
library(tidyverse)
```

```{r}
# Read raw data from csv file into an R dataframe
df <- read.csv("jatos_results_2020.csv")
# df <- read.csv("/path/to/data/file.csv")
```

```{r}
# generate subject id's from timestamps

# make a new column in the data frame for subject ID numbers and fill with the date- and timestamps
df$id <- as.factor(df$datetime)

# change the date- and timestamps to ID numbers, with a new ID number corresponding to each new date- and timestamp
levels(df$id) <- seq(1, length(levels(df$id)))

```

```{r}
# Make a new dataframe with just the variables we are interested in
d <- select(df, id, block, correct, present, setSize, response_time)

# change "n" and "y" to 
d$present <- ifelse(d$present == "n", "NotPresent", "Present")
```

```{r}
# Remove all the practice trials and rename "response_time" as "rt"
experiment <- d %>%
  filter(block != "practice") %>%
  rename(rt = response_time)
  
```

```{r}
# Keep only the correct answers
correct <- experiment %>%
  filter(correct == 1)
```

```{r}
# Find the average response time for each participant in each condition (each set size, and probe both present and absent)
collapsed <- correct %>%
  group_by(setSize, present, id) %>%
  summarize(mRT = mean(rt))
```

```{r}
# Collapse the data further: find the mean response time across participants for each set size with probes present and absent
df_Means <- collapsed %>%
  group_by(setSize, present) %>%
  summarize(m = mean(mRT))
  
```

```{r}
df_Means_wide <- df_Means %>%
  spread(key = present, value = m)
```


While we're at it, let's make some plots from our data

```{r}
# Convert dfMeans from wide format to long format for plotting with ggplot
df_Means_long <- df_Means_wide %>%
  gather(key = Present, value = RT, -setSize)
```

```{r}
# Plot the data, showing points for mean values at each set size
ggplot(df_Means_long, aes(setSize, RT, color = Present)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Sternberg Task (means)",
       y = "RT",
       x = "SetSize") +
  theme_classic()
```

```{r}
# Plot the data, showing points for all values at each set size
ggplot(correct, aes(setSize, rt, color = present)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  labs(title = "Sternberg Task (all data",
       y = "RT",
       x = "SetSize") +
  theme_classic()
```

```{r}
write.csv(df_Means_long, file="data_long.csv", row.names = FALSE)
```

